BADADDR = ...

NN_ja = ...
NN_jae = ...
NN_jb = ...
NN_jbe = ...
NN_jc = ...
NN_jcxz = ...
NN_je = ...
NN_jecxz = ...
NN_jg = ...
NN_jge = ...
NN_jl = ...
NN_jle = ...
NN_jna = ...
NN_jnae = ...
NN_jnb = ...
NN_jnbe = ...
NN_jnc = ...
NN_jne = ...
NN_jng = ...
NN_jnge = ...
NN_jnl = ...
NN_jnle = ...
NN_jno = ...
NN_jnp = ...
NN_jns = ...
NN_jnz = ...
NN_jo = ...
NN_jp = ...
NN_jpe = ...
NN_jpo = ...
NN_jrcxz = ...
NN_js = ...
NN_jz = ...
NN_jmp = ...
NN_jmpfi = ...
NN_jmpni = ...
NN_jmpshort = ...

CF_STOP = ...
CF_CALL = ...
CF_CHG1 = ...
CF_CHG2 = ...
CF_CHG3 = ...
CF_CHG4 = ...
CF_CHG5 = ...
CF_CHG6 = ...
CF_USE1 = ...
CF_USE2 = ...
CF_USE3 = ...
CF_USE4 = ...
CF_USE5 = ...
CF_USE6 = ...
CF_JUMP = ...
CF_SHFT = ...
CF_HLL  = ...

SWI_SPARSE = ...
SWI_V32 = ...
SWI_J32 = ...
SWI_VSPLIT = ...
SWI_RESERVED = ...
SWI_DEF_IN_TBL = ...

ea_t = ...
flags_t = ...
void = ...

class FlowChart(object):
    def __init__(self, f=None, bounds=None, flags=0): ...
    def _getitem(self, index): ...
    def __iter__(self): ...
    def __getitem__(self, index): ...

def get_segm_by_name(*args) -> "segment_t *": ...
def find_not_func(*args) -> "ea_t": ...
def get_func(*args) -> "func_t *": ...
def is_data(*args) -> "bool": ...
def get_full_flags(*args) -> "flags_t": ...
def is_unknown(*args) -> "bool": ...
def get_switch_info(*args): ...
def calc_switch_cases(*args) -> "cases_and_targets_t *": ...